 The actions in the try block is executed first, and if it throws an exception, the actions in the onError block will be executed.